# Generated by Django 2.2 on 2020-10-21 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportInfo',
            fields=[
                ('ReportNumber', models.AutoField(primary_key=True, serialize=False)),
                ('ReportUser', models.CharField(max_length=10)),
                ('ReportDate', models.DateTimeField(null=True, verbose_name='日志时间')),
                ('ReportWork', models.CharField(max_length=1000)),
                ('ReportProblem', models.CharField(max_length=1000)),
                ('ReportPlan', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReportComment', models.CharField(max_length=1000)),
                ('TargetReport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Report.ReportInfo')),
            ],
        ),
    ]
