# Generated by Django 2.2 on 2020-10-22 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReportComment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportsInfo',
            fields=[
                ('ReportNumber', models.AutoField(primary_key=True, serialize=False)),
                ('ReportUser', models.CharField(max_length=10)),
                ('ReportDate', models.DateTimeField(null=True, verbose_name='日志时间')),
                ('ReportWork', models.TextField(blank=True)),
                ('ReportProblem', models.TextField(blank=True)),
                ('ReportPlan', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='ReportInfo',
        ),
        migrations.AddField(
            model_name='comments',
            name='TargetReport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Report.ReportsInfo'),
        ),
    ]
